version: '3.8'

services:
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: tvapp_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017" 
    volumes:
      - ./database/data:/data/db 
    env_file: 
      - .env
