version: "3.8"

services:
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile  # Make sure the Dockerfile exists here
    container_name: tvapp_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db
    env_file: 
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Ensure a Dockerfile exists in ./backend
    container_name: tvapp_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .env:/app/.env

  frontend:
    build:
      context: ./frontend/tvapp-frontend
      dockerfile: Dockerfile  # Ensure a Dockerfile exists in ./tvapp-frontend
    container_name: tvapp_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
