// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model


type Mutation struct {
}


type Query struct {
}

type Author struct {
	Name  string `json:"name" bson:"name"`
	Email string `json:"email" bson:"email"`
}

type News struct {
	ID      string  `json:"id" bson:"_id"`
	Title   string  `json:"title" bson:"title"`
	Content string  `json:"content" bson:"content"`
	Author  *Author `json:"author" bson:"author"`
}
