// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type News struct {
	ID      string  `json:"id"`
	Title   string  `json:"title"`
	Content string  `json:"content"`
	Author  *Author `json:"author"`
}

type Query struct {
}
